# Generated by Django 5.1.7 on 2025-03-12 23:41

import data.custom_fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    data.custom_fields.CustomAutoField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    data.custom_fields.CustomCharField(
                        max_length=10,
                        validators=[django.core.validators.MinLengthValidator(3)],
                        verbose_name="Código",
                    ),
                ),
                (
                    "name",
                    data.custom_fields.CustomCharField(
                        max_length=100, verbose_name="Nombre"
                    ),
                ),
                (
                    "description",
                    data.custom_fields.CustomCharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "price",
                    data.custom_fields.CustomIntegerField(verbose_name="Precio Compra"),
                ),
                ("stock", data.custom_fields.CustomIntegerField(verbose_name="Stock")),
                (
                    "archived",
                    data.custom_fields.CustomBooleanField(
                        default=True, verbose_name="Activo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["name"],
            },
        ),
    ]
